USE [master]
GO

/****** Object:  Database [File_Path_Database]    Script Date: 2/10/2026 10:21:41 PM ******/
CREATE DATABASE [File_Path_Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'File_Path_Database', FILENAME = N'C:\Users\calle\AppData\Local\Microsoft\VisualStudio\SSDT\File_Path_Database.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'File_Path_Database_log', FILENAME = N'C:\Users\calle\AppData\Local\Microsoft\VisualStudio\SSDT\File_Path_Database.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [File_Path_Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [File_Path_Database] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [File_Path_Database] SET ANSI_NULLS ON 
GO

ALTER DATABASE [File_Path_Database] SET ANSI_PADDING ON 
GO

ALTER DATABASE [File_Path_Database] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [File_Path_Database] SET ARITHABORT ON 
GO

ALTER DATABASE [File_Path_Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [File_Path_Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [File_Path_Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [File_Path_Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [File_Path_Database] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [File_Path_Database] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [File_Path_Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [File_Path_Database] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [File_Path_Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [File_Path_Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [File_Path_Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [File_Path_Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [File_Path_Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [File_Path_Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [File_Path_Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [File_Path_Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [File_Path_Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [File_Path_Database] SET RECOVERY FULL 
GO

ALTER DATABASE [File_Path_Database] SET  MULTI_USER 
GO

ALTER DATABASE [File_Path_Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [File_Path_Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [File_Path_Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [File_Path_Database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [File_Path_Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [File_Path_Database] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [File_Path_Database] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [File_Path_Database] SET QUERY_STORE = ON
GO

ALTER DATABASE [File_Path_Database] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [File_Path_Database] SET  READ_WRITE 
GO

