USE [master]
GO

/****** Object:  Database [Nba_Database01]    Script Date: 2/10/2026 10:23:43 PM ******/
CREATE DATABASE [Nba_Database01]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nba_Database01', FILENAME = N'C:\Users\calle\AppData\Local\Microsoft\VisualStudio\SSDT\Nba_Database01.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nba_Database01_log', FILENAME = N'C:\Users\calle\AppData\Local\Microsoft\VisualStudio\SSDT\Nba_Database01.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nba_Database01].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Nba_Database01] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Nba_Database01] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Nba_Database01] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Nba_Database01] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Nba_Database01] SET ARITHABORT ON 
GO

ALTER DATABASE [Nba_Database01] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Nba_Database01] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Nba_Database01] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Nba_Database01] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Nba_Database01] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Nba_Database01] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Nba_Database01] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Nba_Database01] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Nba_Database01] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Nba_Database01] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Nba_Database01] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Nba_Database01] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Nba_Database01] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Nba_Database01] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Nba_Database01] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Nba_Database01] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Nba_Database01] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Nba_Database01] SET RECOVERY FULL 
GO

ALTER DATABASE [Nba_Database01] SET  MULTI_USER 
GO

ALTER DATABASE [Nba_Database01] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Nba_Database01] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Nba_Database01] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Nba_Database01] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Nba_Database01] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Nba_Database01] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Nba_Database01] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Nba_Database01] SET QUERY_STORE = ON
GO

ALTER DATABASE [Nba_Database01] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Nba_Database01] SET  READ_WRITE 
GO

